name: release
on: 
  schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch:

env:
  TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
  TWINE_USERNAME: __token__
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  release:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        #miniforge-variant: Mambaforge
    - name: install dependencies
      run: | 
        conda install -qy anaconda-client conda-build wheel setuptools boa mamba
        pip install -Uqq twine sphinx fastcore pip wheel fastrelease
    - name: parse data & release if appropriate
      run: bash all_actions.sh all
